"""add predicted_bbox and final_bbox to recognition_samples

Revision ID: 5cdb364b8e90
Revises: b62c2d519dd4
Create Date: 2026-08-11 10:49:23.089886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdb364b8e90'
down_revision: Union[str, Sequence[str], None] = 'b62c2d519dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recognition_samples', sa.Column('predicted_bbox', sa.JSON(), nullable=True))
    op.add_column('recognition_samples', sa.Column('final_bbox', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recognition_samples', 'final_bbox')
    op.drop_column('recognition_samples', 'predicted_bbox')
    # ### end Alembic commands ###
