"""initial recognition tables

Revision ID: b62c2d519dd4
Revises: 
Create Date: 2026-08-10 19:32:37.341873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62c2d519dd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognition_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_threshold', sa.Float(), nullable=False),
    sa.Column('crop_padding_ratio', sa.Float(), nullable=False),
    sa.Column('max_retained_scan_images', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recognition_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['recognition_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'name', name='uq_instance_entity_name')
    )
    op.create_table('recognition_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('predicted_instance_id', sa.Integer(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('predicted_bbox', sa.JSON(), nullable=True),
    sa.Column('final_instance_id', sa.Integer(), nullable=True),
    sa.Column('final_bbox', sa.JSON(), nullable=True),
    sa.Column('annotation_status', sa.Enum('pending_review', 'confirmed', name='annotationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['final_instance_id'], ['recognition_instances.id'], ),
    sa.ForeignKeyConstraint(['predicted_instance_id'], ['recognition_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['recognition_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recognition_samples')
    op.drop_table('recognition_predictions')
    op.drop_table('recognition_instances')
    op.drop_table('recognition_entities')
    op.drop_table('recognition_config')
    # ### end Alembic commands ###
